sudo: false

language: elm

cache:
  directories:
    - cache
    - sysconfcpus
    - node_modules
    - elm-stuff/build-artifacts

install:
  - make install

script:
  - make clean setup build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
